# Project
project_name: "TestDiff"

# Input and output paths
input_path: "data/HO_data_filtered/HumanOrigins2067_filtered.parquet"
output_path: "outputs"

# Time Sampler
time_sampler:
  tmin: 1
  tmax: 1000

# DDPM
diffusion:
  diffusion_steps: 1000
  beta_start: 0.0001
  beta_end: 0.02

# UNet1D
unet:
  embedding_dim: 128       # Reduced from 128
  dim_mults: [1, 2, 4, 8]  # Reduced from [1, 2, 4, 8]
  channels: 1
  with_time_emb: true
  with_pos_emb: false
  resnet_block_groups: 8

# Dataset
data:
  seq_length: 160858      # Reduced from 160858
  batch_size: 64          # Reduced from 64
  num_workers: 4
  datasplit: [1700, 200, 167]

# Training
training:
  epochs: 50
  early_stopping: false
  patience: 10
  save_top_k: 3
  num_samples: 10
  logger: "wandb"
  log_every_n_steps: 25

# Optimizer
optimizer:
  lr: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8
  amsgrad: true

# Scheduler
scheduler:
  name: "cosine"
  T_max: 50  # Same as max_epochs
  eta_min: 1e-6
