# Project
project_name: "GenDiffusion"

# Input and output paths
input_path: "data/HO_data_filtered/HumanOrigins2067_filtered.parquet"
output_path: "output"

# Time Sampler
time_sampler:
  tmin: 1
  tmax: 1000

# DDPM
diffusion:
  num_diffusion_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02


# UNet1D
unet:
  embedding_dim: 32
  dim_mults: [1, 2, 4]  # Reduced from [1, 2, 4, 8]
  channels: 1
  with_time_emb: true
  resnet_block_groups: 8

# Dataset
data:
  seq_length: 2067
  batch_size: 256
  num_workers: 4
  split: [0.8, 0.1, 0.1]

# Training
training:

  # Core training settings
  num_epochs: 100
  gradient_clip_val: 1.0
  
  # Checkpoint settings
  save_top_k: 3
  
  # Performance optimization
  gradient_checkpointing: true
  grad_accum: 2
  val_check_interval: 0.5  # Validate twice per epoch
  
  # Early stopping
  patience: 10
  test_threshold: 0.1
  
  # Learning rate schedule
  warmup_epochs: 5
  
  # Sample generation
  num_samples: 10

  # Logger
  logger: "wandb"

# Optimizer
optimizer:
  name: "adamw"
  lr: 1.0e-4
  min_lr: 1.0e-6
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1.0e-8
  amsgrad: true
