# Project
project_name: "GenDiffusion"

# Input and output paths
input_path: "data/HO_data_filtered/HumanOrigins2067_filtered.parquet"
output_path: "output"

# Time Sampler
time_sampler:
  tmin: 1
  tmax: 1000

# DDPM
diffusion:
  num_diffusion_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

# UNet1D
unet:
  embedding_dim: 32
  dim_mults: [1, 2, 4]  # Reduced from [1, 2, 4, 8]
  channels: 1
  with_time_emb: true
  resnet_block_groups: 8

# Dataset
data:
  seq_length: 2067
  batch_size: 256
  num_workers: 4
  split: [0.8, 0.1, 0.1]

# Training
training:
  epochs: 10
  early_stopping: true
  patience: 10
  save_top_k: 3
  compute_test_metrics: true
  test_threshold: 0.1
  num_samples: 10
  logger: "wandb"  # Options: wandb, tb, csv

# Optimizer
optimizer:
  lr: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8
  amsgrad: true

# Scheduler
scheduler:
  name: "cosine"
  T_max: 100  # Same as max_epochs
  eta_min: 1e-6
