# Project name
project_name: "FinDiff"

# Project output
output_path: "${PROJECT_ROOT}/outputs"

# Dataset
data:
  input_path: "${PROJECT_ROOT}/data/HO_data_filtered/HumanOrigins2067_filtered.parquet"
  batch_size: 64
  num_workers: 4
  datasplit: [1700, 200, 167]

  # Preprocessing Tasks
  seq_length: 100              # Total length is 160858
  missing_value: 9             # None, to not handle missing values
  normalize: true
  scaling: true
  scale_factor: 0.5
  augment: true

# Time Sampler
time_sampler:
  tmin: 1
  tmax: 1000

# DDPM
diffusion:
  timesteps: 1000              # Diffusion steps, should match tmax?
  beta_start: 0.0001           # Start value for linear beta scheduler
  beta_end: 0.02               # End value for linear beta scheduler
  max_beta: 0.999              # Maximum value for cosine beta scheduler
  schedule_type: "cosine"      # Schedule type (linear/cosine)
  denoise_step: 1
  discretize: False

# UNet1D
unet:
  embedding_dim: 128           # Reduced from 128
  dim_mults: [1, 2, 4, 8]      # Reduced from [1, 2, 4, 8]
  channels: 1
  with_time_emb: false
  with_pos_emb: false
  resnet_block_groups: 8

# Training
training:
  epochs: 50
  early_stopping: false
  patience: 10
  save_top_k: 3
  num_samples: 10
  logger: "wandb"
  log_every_n_steps: 25

# Optimizer
optimizer:
  lr: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8
  amsgrad: true

# Scheduler
scheduler:
  name: "cosine"
  eta_min: 1e-6
